// Tablet play: every step done with the on-screen buttons only, no keyboard.
import { start } from './harness.mjs';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const out = process.argv[2] ?? fs.mkdtempSync(path.join(os.tmpdir(), 'alicorn-touch-'));
const h = await start(undefined, { touch: true });
let ok = true;
const check = (label, cond) => { console.log(`${cond ? '✓' : '✗'} ${label}`); ok &&= !!cond; };
const BTN = { left: [94, 626], right: [254, 626], up: [174, 496], star: [1166, 546], down: [1006, 626], esc: [74, 226] };
const tap = async (b) => { await h.page.touchscreen.tap(...BTN[b]); await h.wait(450); };
const hold = async (b, ms) => { await h.page.mouse.move(...BTN[b]); await h.page.mouse.down(); await h.wait(ms); await h.page.mouse.up(); };
const active = (k) => h.page.evaluate((k) => window.game.scene.isActive(k), k);
const hero = () => h.page.evaluate(() => { const p = window.game.scene.getScene('World').player; return { x: Math.round(p.x), y: Math.round(p.y) }; });

await h.wait(3000);
check('buttons show on a touch screen', await h.page.evaluate(() => window.game.scene.getScene('Touch').layer.visible));
await h.shot(out, 'touch-1-title');
await tap('star'); await h.wait(1200);
check('★ on the title starts a new player', await active('NamePicker'));
await tap('right'); await tap('star'); await h.wait(2500);
check('★ picks a name and goes Home', await active('World'));
const a = await hero();
await hold('right', 1200); await h.wait(300);
const b = await hero();
check('holding ▶ walks right', b.x > a.x + 100);
await tap('star'); await h.wait(150);
const c = await hero();
check('★ flaps up', c.y < b.y - 20);
await h.wait(1500);
await h.page.evaluate(() => window.alicorn.teleport('door-skymap')); await h.wait(600);
await h.shot(out, 'touch-2-star-gate');
await tap('down'); await h.wait(2000);
check('⬇ at the Star Gate opens the Sky Map', await active('SkyMap'));
await tap('right'); await tap('down'); await h.wait(2500);
check('▶ then ⬇ lands in the Enchanted Forest', (await h.page.evaluate(() => window.game.scene.getScene('World').level?.id)) === 'forest-hub');
await tap('esc'); await h.wait(900);
check('✕ opens the Adventure Book', await active('StickerBook'));
await h.shot(out, 'touch-3-book');
await tap('esc'); await h.wait(700);
check('✕ closes it again', !(await active('StickerBook')) && (await active('World')));
console.log('screens in', out);
console.log('ERRORS', h.errors.join('\n') || 'none');
await h.browser.close();
process.exit(ok && !h.errors.length ? 0 : 1);
